# Initially generated by GitHub Copilot.
"""Toy example: survey the templates used in Samuel.

When run from the MAM-parsed repo root:

    python py-examples/main_tmpl_survey_toy_example.py
"""

from mb_misc import tmpl_survey_toy


def main():
    """Survey the templates used in Samuel."""
    tmpl_survey_toy.almost_main("plain/BA-Samuel.json")


if __name__ == "__main__":
    main()
