# Initially generated by GitHub Copilot.
"""Toy example: survey the templates used in a MAM-parsed plus JSON book."""

import collections
import json
import os

_MINIROW = collections.namedtuple("Minirow", "C, D, E")


def _openw(path, **kwargs):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return open(path, "w", encoding="utf-8", newline="", **kwargs)


def _param_val_as_list(val):
    """Normalize a tmpl_params value to a list of wtel elements.

    In the plus JSON, a param value may be stored as a bare string, a bare
    template dict (singleton shorthand), or a full list.  Wrap the first two
    cases so callers always iterate a list.
    """
    if isinstance(val, (str, dict)):
        return [val]
    assert isinstance(val, list)
    return val


def _record(survey, wtel, column_letter):
    if isinstance(wtel, str):
        return
    assert isinstance(wtel, dict) and "tmpl_name" in wtel
    tmpl_name = wtel["tmpl_name"]
    survey.add((tmpl_name, column_letter))
    for val in wtel.get("tmpl_params", {}).values():
        for arg_wtel in _param_val_as_list(val):
            _record(survey, arg_wtel, column_letter)


def _keyfn(record):
    return tuple(record.values())


def _do_survey(book39s):
    # chapent: chaptered entity (book or sub-book)
    survey = set()
    for chapent in book39s:
        for chapter in chapent["chapters"].values():
            for psv_contents in chapter.values():
                minirow = _MINIROW(*psv_contents)
                for wtel in minirow.C:
                    _record(survey, wtel, "C")
                for wtel in minirow.E:
                    _record(survey, wtel, "E")
    return survey


def _reformat_survey(survey):
    records = [{"tmpl_name": k[0], "column_letter": k[1]} for k in survey]
    return sorted(records, key=_keyfn)


def almost_main(plus_path):
    """Survey the templates used in the given MAM-parsed plus JSON book."""
    with open(plus_path, encoding="utf-8") as fpi:
        book24 = json.load(fpi)
    survey = _do_survey(book24["book39s"])
    records = _reformat_survey(survey)
    with _openw("./py-examples-out/tmpl_survey_toy.json") as fpo:
        dump_opts = {"indent": 0, "ensure_ascii": False}
        json.dump(records, fpo, **dump_opts)
